### ISSUE TITLE
about comparison

### ISSUE THREAD

**Issue by duzhenjiang113** [zhijieW-94/SAGNet#7]
You compared with G2LGAN during the comparison, but the data set used by G2LGAN is different. How do you handle this data set uniformly? Are there relevant references and codes, thank you
Looking forward to your reply

**Comment by duzhenjiang113** [comment]
i also have a quesion is that the geometry's encoder and structure's DNN network is pre-trained?

**Comment by zhijieW94** [comment]
Sorry for my late responses. 

To make a comparison between G2LGAN and our SAGNet, we write some simple scripts to transform the data of two methods into the same form. For the metrics of MMD/COV as well as Inception scores, we convert all the data of both G2LGAN and SAGNet into point clouds with the same scales. But in terms of R_{over}, we convert the data of G2LGAN to our shape representation because we need the values of bounding boxes for computation. I aimed to search relevant codes in my own laptop to give you more specific information but unfortunately no back-ups were found. And I have left the lab for a long time, so I am afraid I cannot offer the codes for you at this point. 

In addition, we train our whole SAGNet from scratch and did not use any pre-trained model.

**Comment by duzhenjiang113** [comment]
> Sorry for my late responses.
> To make a comparison between G2LGAN and our SAGNet, we write some simple scripts to transform the data of two methods into the same form. For the metrics of MMD/COV as well as Inception scores, we convert all the data of both G2LGAN and SAGNet into point clouds with the same scales. But in terms of R_{over}, we convert the data of G2LGAN to our shape representation because we need the values of bounding boxes for computation. I aimed to search relevant codes in my own laptop to give you more specific information but unfortunately no back-ups were found. And I have left the lab for a long time, so I am afraid I cannot offer the codes for you at this point.
> In addition, we train our whole SAGNet from scratch and did not use any pre-trained model.

thanks
